name: Docker ğŸ‹

on:
  push:
    paths:
      - 'docker/**'
  workflow_dispatch:

jobs:
  build:
    name: Docker ğŸ‹

    runs-on: ubuntu-20.04

    steps:
    - name: Login to DockerHub ğŸ”Œ
      uses: docker/login-action@v2.1.0
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
      name: ğŸ”„ Checkout Code
      with:
          ref: master
    - run: cd docker && docker build -t empathicqubit/vscode-cc65-debugger-build .
      name: ğŸ› ï¸ Build GHA runner image
    - run: cd docker && docker build -t empathicqubit/vscode-cc65-debugger-devcontainer -f devcontainer.Dockerfile .
      name: ğŸ› ï¸ Build devcontainer image
    - run: docker push empathicqubit/vscode-cc65-debugger-build
      name: â¬†ï¸ Push GHA runner image
    - run: docker push empathicqubit/vscode-cc65-debugger-devcontainer
      name: â¬†ï¸ Push devcontainer image
